### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by mattl** [boriel-basic/zxbasic#206]
You have GPLv3 in the repo.

You link to a GPLv3 button on the README.

You say it's LGPL-llke.

You have some Emacs-commune like requirements.

**Comment by boriel** [comment]
ZX Basic was originally GPLv3, but that was a problem because the generated binaries injects asm / basic code which is in library-asm/ and library/ respectively.

Hence, to allow people to make closed source redistributable binaries using that runtime code, these 2 folders and its related content are licensed MIT.

That of LGPL-like must be a reminiscence of versions prior 1.4.x and must tb removed. Will change that.

**Comment by donaldr3** [comment]
You may want to take a look at how GNU Bison handled similar issues, see <http://git.savannah.gnu.org/cgit/bison.git/tree/src/parse-gram.c> and <https://www.gnu.org/licenses/gpl-faq.en.html#CanIUseGPLToolsForNF>. You'll also want to take a look at <https://www.gnu.org/licenses/gpl-howto.en.html> for instructions on license notices.

**Comment by Jookia** [comment]
Just saw this issue, and there's an answer in #695 : The license is AGPL with an additional restriction listed in the README:

"If you modify this project (the compiler .py or anything licensed as AGPLv3) in any and use it as a part of a SaaS service, you MUST publish the changes you made and submit your contribution to the community under the same license."

This restriction is allowed to be ignored based on the AGPLv3 license.

**Comment by Jookia** [comment]
Just for reference there is a further elaboration of the licensing situation in #695 . It's still confusing to me, but maybe it clear things up.

**Comment by boriel** [comment]
> Just for reference there is a further elaboration of the licensing situation in #695 . It's still confusing to me, but maybe it clear things up.

No. It's explained here:
https://opensource.stackexchange.com/questions/13256/using-agpl-package-for-a-saas

Basically if you can have compiler code isolated (e.g. in a Docker container or in a separate directory -unmodified-) the that's ok.

But if you modify the compiler in a SaaS to be used publicly by users those changes must be made public under the same license too.

**Comment by Jookia** [comment]
I deleted my comments, I don't need a response: I'm confused, and I was just trying to point to that issue for reference to aid anyone else confused about the supposed contradiction like I am.

**Comment by boriel** [comment]
I think we can close this issue:
As of v1.17.3 onwards, the compiler is licensed aGPL v3. 
The library files (ie. those use to created compiled programs) are released under Apache / MIT / BSD / Public domain licenses (i.e. to allow people to create closed-source / commercial programs, like videogames).

**Comment by Jookia** [comment]
This clause is in conflict with the AGPL license:

"If you modify this project (the compiler .py or anything licensed as AGPLv3) in any and use it as a part of a SaaS service, you MUST publish the changes you made and submit your contribution to the community under the same license."

I've tried to explain this but I think I've come off as a troll 😅

Nov 17, 2024 01:52:30 Jose Rodriguez ***@***.***>:

**Comment by boriel** [comment]
And I have already explained you that you always "can" modiffy the program.
The aGPL states that you only have to publish your changes whenever you use the program as a service (SaaS).
If you don´t want to do that, you can simply put the compiler in a separate directory and invoke it within your service and that's all.
I don´t see any problem, to be honest.

**Comment by Jookia** [comment]
The AGPL says you only have to publish your changes to the people who use your program, not the entire Internet or 'community'. There is no requirement for you to publish your code on say GitHub or send patches here. The AGPL says explicitly that additional requirements like these can be ignored.

The AGPL has the same wording here as the GPL, but it's hard to find anything about this because it's not in the license.

Regarding what I'm trying to do is get clarification: You say I MUST do something that the license says I can do. I like your software, and I want to use it, but I don't want to betray your wishes as an author- you clearly want something that the license forbids, and that's not great for anyone.

**Comment by boriel** [comment]
"With the people that interacts with your program". That is. :-)
I was about to say that the last paragraph of the StackOverflow link provided, indeed states:

> In answer to the question in the title: you must share such modified software - and not just your modifications, but the complete corresponding source - with anyone to whom you distribute any portion of the software, and with anyone who interacts with your modified version over a computer network.

And this exactly what I've been trying to state from the beginning. And again, this is about _the compiler_ (the Python code), not the programs created with it.

Anyway, we (yes, I have contacted back the contributors) are rearranging this for the upcoming version to put it clearer.

**Comment by Jookia** [comment]
Yes but "you MUST publish the changes you made and submit your contribution to the community under the same license" goes beyond those requirements and involves the 'community', which isn't really defined anywhere in the license. It requires releasing source code to people who aren't using your project.

As a clear example: Say I host a SaaS on my LAN with zxbasic changes, and friends use it. The wording you've put requires me to publish my changes and give them to the community even though they haven't even used my software. The AGPL doesn't require this and says that additional restrictions like these (you must publish changes to the community) can be ignored. Which isn't what you want is it?

Yes, you can argue that not publishing changes is a jerk move and I would agree. I'm an active open source contributor and contribute to GPL projects and deal with the pains of people violating the GPL every day and hurting end users and developers. 

But the problem here is that this additional restriction on the use of your software effectively makes zxbasic's compiler non-free and incompatible with other GPL and AGPL code.

You seem to want a license that requires people to share any changes they make and push out to production which isn't what the AGPL is. You would need to choose a different, non-free license that has the constraint.

**Comment by Jookia** [comment]
Okay, so it's AGPL and that's the only part that I have to legally follow? The README doesn't have any legal implications? Great, I think that does solve this issue and my question.

**Comment by mattl** [comment]
I will admit it’s confusing how the README is written. But I’m glad the license is settled. 

Thank you for your work.
